CREATE TABLE project_attachments
(
    id         BIGINT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,
    link       VARCHAR(255)   NOT NULL,
    type       VARCHAR(255) ,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME  DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL
);