CREATE TABLE tags
(
    id         BIGINT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,
    name       VARCHAR(255)   NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME  DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL
);